wandb_version: 1

learning_rate:
  desc: null
  value: 0.0002
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 3
gradient_accumulation_steps:
  desc: null
  value: 2
optimizer:
  desc: null
  value: paged_adamw_32bit
max_grad_norm:
  desc: null
  value: 0.3
warmup_ratio:
  desc: null
  value: 0.03
lr_scheduler_type:
  desc: null
  value: cosine
weight_decay:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.17.7
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724088076
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.2
      5: 0.17.7
      6: 4.44.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
